name: Validate training workflow

on:
  - pull_request
  - push

jobs:
  build_docker_images:
    name: Validate Docker images
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Start containers
        run: |
          cd docker_environment/
          docker-compose build

  validate_training:
    name: Test training changes
    needs: build_docker_images
    container:
      image: conan_training_env_conan-training:latest
      steps:
        - uses: actions/checkout@v3
          with:
            fetch-depth: 2
        - uses: actions/setup-python@v3
          with:
            python-version: 3.6
        - name: Install dependencies
          run: pip install tox tox-venv
        - name: Execute Tox
          env:
            TOXENV: py36-conan
          run: tox -vvv
