name: Validate training workflow

on:
  - pull_request
  - push

jobs:
  validate_training:
    name: Validate Training changes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Build images
        run: |
          cd docker_environment/
          docker-compose build
      - name: Start docker container
        run: docker run -d -t -v ${PWD}:/home/conan/project --name training conan_training_env_conan-training:latest
      - name: Install tox
        run: docker exec training pip install -U tox tox-venv
      - name: Run tests
        run: docker exec -e TOXENV=py37-conan training tox -vvv project/
